Atividade da Aula 10 - Matemática Computacional - Adiel Dos Santos Nascimento - 201504940002

In [4]:
#Importações necessárias
import numpy as np

Tarefa 1:

In [17]:
def calcularM(MatrizA,n): 
    matriz12 = MatrizA[ 2 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ]
    matriz21 = MatrizA[ 3 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ] 
    
    return matriz12, matriz21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
n = np.shape(A)[0] - 1

a, b = calcularM(A,n)

M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])
matrizFinal = M * A

print('------------ Matriz Inicial -----------')
print(M)
print('\n')

print('------------ Matriz Final -----------')
print(matrizFinal)

------------ Matriz Inicial -----------
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


------------ Matriz Final -----------
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


Tarefa 2

In [19]:
def calcularM(MatrizA,n): 
    matriz12 = MatrizA[ 2 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ]
    matriz21 = MatrizA[ 3 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ] 
    
    return matriz12, matriz21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
b = np.array([1,2,3])

n = np.shape(A)[0] - 1
a,b = calcularM(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print('------------ Matriz Usando dot -----------')
print(np.dot(M,b))

------------ Matriz Usando dot -----------
[[ 1.33333333  0.          0.        ]
 [-0.44444444  1.33333333  0.        ]
 [-1.77777778  0.          1.33333333]]
