Atividade da Aula 10 - Matemática Computacional - Adiel Dos Santos Nascimento - 201504940002

Referência : https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/livro-py.pdf

In [3]:
#Importações necessárias
import numpy as np

Tarefa 1:

In [17]:
def calcularM(MatrizA,n): 
    matriz12 = MatrizA[ 2 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ]
    matriz21 = MatrizA[ 3 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ] 
    
    return matriz12, matriz21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
n = np.shape(A)[0] - 1

a, b = calcularM(A,n)

M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])
matrizFinal = M * A

print('------------ Matriz Inicial -----------')
print(M)
print('\n')

print('------------ Matriz Final -----------')
print(matrizFinal)

------------ Matriz Inicial -----------
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


------------ Matriz Final -----------
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


Tarefa 2

In [19]:
def calcularM(MatrizA,n): 
    matriz12 = MatrizA[ 2 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ]
    matriz21 = MatrizA[ 3 - 1, 1 - 1 ] / MatrizA[ 1 - 1, 1-1 ] 
    
    return matriz12, matriz21
  
A = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
b = np.array([1,2,3])

n = np.shape(A)[0] - 1
a,b = calcularM(A,n)
M = np.matrix([[1,0,0],[(a*(-1)),1,0],[(b*(-1)),0,1]])

print('------------ Matriz Usando dot -----------')
print(np.dot(M,b))

------------ Matriz Usando dot -----------
[[ 1.33333333  0.          0.        ]
 [-0.44444444  1.33333333  0.        ]
 [-1.77777778  0.          1.33333333]]


In [7]:
def calculaMulti(A):
    Matriz1 = np.zeros(np.shape(A)[0])
    
    for i in range(1, np.shape(A)[0]):
        Matriz1[i] = A[i,1]/A[i-1,1]
    
    Matriz2 = np.zeros((np.shape(A)[0], np.shape(A)[1]))
    
    for i in range(0, np.shape(A)[0]):
        Matriz2[i,i] = 1
    
    for i in range(2, np.shape(A)[0]):
        Matriz2[i,1] = -Matriz1[i]
    
    MatrizResultado = Matriz1 * Matriz2
    return MatrizResultado

A = np.matrix([[3,2,4], [1,1,2], [4,3,-2]])

print('Resultado:')
print (calculaMulti(A))
    
    
    

Resultado:
[[ 0.   0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.  -1.5  3. ]]


In [12]:
def fatoraLU(A):
    U = np.copy(A)
    n = np.shape(U)[0]
    L = np.eye(n)
    for j in np.arange(n-1):
            for i in np.arange(j+1,n):
                L[i,j] = U[i,j]/U[j,j]
                for k in np.arange(j+1,n):
                    U[i,k] = U[i,k] - L[i,j]*U[j,k]
                U[i,j] = 0
    return L, U
    
    
A = np.matrix([[3,2,4], [1,1,2], [4,3,-2]],dtype=float)
b = np.array([1,2,3])

print('Resultado:')
print (fatoraLU(A))

Resultado:
(array([[1.        , 0.        , 0.        ],
       [0.33333333, 1.        , 0.        ],
       [1.33333333, 1.        , 1.        ]]), array([[ 3.        ,  2.        ,  4.        ],
       [ 0.        ,  0.33333333,  0.66666667],
       [ 0.        ,  0.        , -8.        ]]))
